### ISSUE TITLE
Compilation error on Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by huongoss** [NVIDIAGameWorks/NRDSample#17]
I use these to build:
mkdir build
cd build; cmake ..
make -j2

[ FAIL ] SPIRV TraceAmbient.cs.hlsl {main} {}
dxc: ./external/SPIRV-Tools/source/opt/pass.cpp:145: uint32_t spvtools::opt::Pass::GenerateCopy(spvtools::opt::Instruction*, uint32_t, spvtools::opt::Instruction*): Assertion `false && "Don't know how to copy this type.  Code is likely illegal."' failed.
Aborted (core dumped)
[ 88%] Building CXX object External/NRD/CMakeFiles/NRD.dir/Source/Reblur.cpp.o
[ FAIL ] SPIRV TraceTransparent.cs.hlsl {main} {}
dxc: ./external/SPIRV-Tools/source/opt/pass.cpp:145: uint32_t spvtools::opt::Pass::GenerateCopy(spvtools::opt::Instruction*, uint32_t, spvtools::opt::Instruction*): Assertion `false && "Don't know how to copy this type.  Code is likely illegal."' failed.
Aborted (core dumped)
[ FAIL ] SPIRV TraceOpaque.cs.hlsl {main} {}
dxc: ./external/SPIRV-Tools/source/opt/pass.cpp:145: uint32_t spvtools::opt::Pass::GenerateCopy(spvtools::opt::Instruction*, uint32_t, spvtools::opt::Instruction*): Assertion `false && "Don't know how to copy this type.  Code is likely illegal."' failed.
Aborted (core dumped)

**Comment by dzhdanNV** [comment]
A compiler issue, it's on the side of VK SDK. Try to update to the latest.

**Comment by dzhdanNV** [comment]
`TraceAmbient` pass has been replaced with SHARC radiance cache.
