### ISSUE TITLE
Understanding differences between NRDSample and RTX-Path-Tracing

### ISSUE THREAD

**Issue by alex-mat** [NVIDIAGameWorks/NRDSample#20]
Hello,

I have a hard time understanding which code sample is the most representative of a good path tracing framework.
While it is my understanding that RTX-Path-Tracing has more features such as Transmittance, better quality of life features with things like auto exposure, easier interface and functional windowing, both samples seem to have the same goal.
Furthermore, I have observed better performance and visuals in NRDSample along with continuous repo updates, while RTX-Path-Tracing has not been updated for half a year and uses old SDKs.

Please help me understand where should I invest my time in order to understand but also implement good path tracing features for my projects.

Regards,
Alex

**Comment by dzhdanNV** [comment]
I will answer to this as soon as I familiarize myself with latest PTSDK sample (sorry, didn't look for a while). Will do tomorrow.

**Comment by dzhdanNV** [comment]
I would prefer to answer using screenshots to avoid misleading. But in short:
- the purpose of NRD sample, beside demonstrating NRD best practices, is to prove that multi-bounce path tracing can be fast
- the purpose of PTSDK is to provide all NVIDIA technologies integrated into a single app
Hope everyone finds something useful in both apps.
![image](https://github.com/user-attachments/assets/11416d56-e08d-488d-b6b4-c5740d2f9fb6)
![image](https://github.com/user-attachments/assets/4e98c9cf-f29e-42ca-b747-19282f9e8862)
![image](https://github.com/user-attachments/assets/748a9e62-23bc-4e13-830c-b85a15ae4e6a)
![image](https://github.com/user-attachments/assets/8b25292e-863b-4bd0-b8df-a81ac9c2067e)

**Comment by alex-mat** [comment]
I understand. Hopefully RTX-Path-Tracing gets updated.

Thank you !
