### ISSUE TITLE
Support for adding/removing models at runtime

### ISSUE THREAD

**Issue by alex-mat** [NVIDIAGameWorks/NRDSample#21]
Hello,

It would be nice to have a good example of how to add and remove meshes/BLAS at runtime, especially since the readme mentions that we should track memory.
A good use case would be when enabling/disabling animated cubes instead of having them created when scene is loaded.
It would also allow to extend the sample in the future with loading multiple objects, would fit the context of a game integration sample, since a game makes more often than not use of dynamic objects, and would ease integration.

Regards,
Alex

**Comment by dzhdanNV** [comment]
NRD sample has two purposes:
- denoising development and testing (i.e. for NRD)
- path tracing best practices
Loading / uploading of dynamic objects (which are here, as you noted, as well as animation) is outside of this scope. It will increase complexity of BVH management without giving a significant bonus in something else in exchange.

I would close as "won't do" if you don't mind.

**Comment by alex-mat** [comment]
Thank you for the quick answer!

I understand, would be nice to have for quick validation but I can seehow it can be out of scope of the project.

However I believe it could be beneficial for maintainability even as a dev project to slightly extend model handling and have loading of objects be a side effect of this change (not ideal but just rebuilding all acceleration structures when adding an object would be enough), since right now things are hardcoded (such as animated cubes) and make code harder to follow.
RTX-Path-Tracing has a similar problem which makes quick and dirty experimentation difficult.
