### ISSUE TITLE
CMake / packman build issue

### ISSUE THREAD

**Issue by manuelk** [NVIDIAGameWorks/NRDSample#7]
getting this error:
````
CMake Error at External/NRIFramework/CMakeLists.txt:50 (message):
  Packman result: Access is denied (platform: 'windows-x86_64')
````
all other packman downloads work, except this one.

unfortunately i was unable to figure out why this packman command fails when invoked from cmake (checked all the arguments & everything appears to be correct)

however, i was eventually able to work around it the issue by running the same command from the CLI, and commenting the offending segment out of External/NRIFramework/CMakeLists.txt to complete the build configuration (ie. i got the sample to run)

**Comment by dzhdanNV** [comment]
@manuelk Hi! Are you running on Linux?

**Comment by dzhdanNV** [comment]
Git modifies file attributes. I don't think that it's a problem of the repo or code.

**Comment by manuelk** [comment]
it is a problem for the user if cmake cannot execute scripts due to incorrect file permissions 

and git at least does track execution attributes unless it is turned off (and unlike p4 that tracks everything) :
https://mirrors.edge.kernel.org/pub/software/scm/git/docs/git-config.html

**Comment by dzhdanNV** [comment]
I don't follow. There is no "execute" permission on files in Windows. On Linux you have cast "chmod" spell on `Deploy.sh` only, because it casts `chmod` on other scripts. At this point I would like to ask - what I need to do to improve?

**Comment by dzhdanNV** [comment]
(silent close)
