### ISSUE TITLE
CmakeLists Packman file capitalization

### ISSUE THREAD

**Issue by ThomasConrad** [NVIDIAGameWorks/NRDSample#9]
In the CMakeLists.txt, line 41 it looks for packman at this dir `${CMAKE_CURRENT_SOURCE_DIR}/External/Packman/Packman${PACKMAN_EXT}"`. However, after adding the submodules, the actual path turned out to be `${CMAKE_CURRENT_SOURCE_DIR}/External/Packman/packman${PACKMAN_EXT}"`

**Comment by dzhdanNV** [comment]
Thanks! Fixed!
